version: 2

python:
  version: "3.7"
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true
